### PR TITLE
[FLINK-34930] Fork existing code from bahir-flink

### PR DESCRIPTION
**Pull request by ferenc-csaky**
For this step, I tried to not introduce changes in the ported logic. I separated semantically different changes into multiple commits, so the [FLINK-34930] prefixed commits summarize the actual changes.

The spotless and checkstyle changes are fairly big, but most of the stuff were about adding javadoc and code/import reformat.

### TODO
- [x] Explicitly state in the repo that the code was forked from [bahir-flink](https://github.com/apache/bahir-flink).

### CODE REVIEW

**Comment by ferenc-csaky** [comment]
@MartijnVisser can you trigger another CI run pls?

**Comment by ferenc-csaky** [comment]
I am not sure about the current failure with the 1.18.1 + JDK17 combo, I could not reproduce it locally, maybe there is some flakiness here.

**Comment by ferenc-csaky** [comment]
After I took a look at the logs, the error was environmental, it failed to connect to the Dockerized Kudu:
```
ERROR org.apache.kudu.client.Connection [] - [peer master-0:0:0:0:0:0:0:1/<unresolved>:32780(0:0:0:0:0:0:0:1/<unresolved>:32780)] server sent error Service unavailable: service kudu.master.MasterService not registered on TabletServer
```

@MartijnVisser can that one case be retriggered? Or of not, I hope another run would be green.

**Comment by MartijnVisser** [comment]
> @MartijnVisser can that one case be retriggered? Or of not, I hope another run would be green.

Re-triggered all failing jobs!

**Comment by ferenc-csaky** [comment]
Thanks, it passed now! is it okay to merge this change at this point for now?

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@ferenc-csaky I was double checking for legal implications (since this is coming from the Bahir project, that's in the attic). 

Looking at https://issues.apache.org/jira/browse/LEGAL-584?focusedCommentId=17402556&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17402556 I think what's missing in this PR are the actual LICENSE and NOTICE files. WDYT?

**Comment by MartijnVisser** [comment]
@ferenc-csaky I've asked the Legal team for a confirmation on this topic, since the ASF owns both Bahir and Flink code. You can track https://issues.apache.org/jira/browse/LEGAL-675

**Comment by ferenc-csaky** [comment]
> @ferenc-csaky I've asked the Legal team for a confirmation on this topic, since the ASF owns both Bahir and Flink code. You can track https://issues.apache.org/jira/browse/LEGAL-675

Thank you for taking the time and look into it! For the time being, I migrated the Bahir header to the NOTICE. If it is okay to change it, I'll remove that commit.

**Review by MartijnVisser — APPROVED** [review]
I've compared this PR to https://github.com/apache/bahir-flink/commits/master/flink-connector-kudu and it looks complete; https://issues.apache.org/jira/browse/LEGAL-675 also confirmed that we didn't do anything with the NOTICE files. LGTM

**Pull request merged**
